services:
  online_store_database:
    build: 
      context: ./docker/database
      dockerfile: Dockerfile
    volumes:
      - myData:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: 
      context: ./docker/web
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${WEB_POSTGRES_NAME}
      - POSTGRES_USER=${WEB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${WEB_POSTGRES_PASSWORD}
    depends_on:
      - online_store_database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - dataPg:/var/lib/pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - online_store_database

volumes:
  myData:
  dataPg: